### PR TITLE
Issue #1222: Add copy below the input stating file type and size restrictions for Pet Attachments

### PR DESCRIPTION
**Pull request by jasonwang7517**
# 🔗 Issue
[Add copy below the input stating file type and size restrictions](https://github.com/rubyforgood/homeward-tails/issues/1222)

# ✍️ Description
Adds copy below Pet Files and Attachments tab to inform users of file type and size restrictions.

Also changes plurality of hero images to reflect file size of 1.

# 📷 Screenshots/Demos
_New text under pet files_
image

_New text under pet photos_
image

_New singular hero image text_
image

### CODE REVIEW

**Comment by kasugaijin** [comment]
@jasonwang7517 per my comment on the other PR - please also add these on the Pet tabs for files and images (see issue). Thanks!

**Comment by kasugaijin** [comment]
@all-contributors
please add @jasonwang7517 for code.

**Comment by jasonwang7517** [comment]
> @jasonwang7517 thank you!

heck yeah officially an open-source contributor

**Comment by kasugaijin** [comment]
> > @jasonwang7517 thank you!
> 
> heck yeah officially an open-source contributor

This is just the start :)

**Pull request merged**
