### PR TITLE
#1082: Make filter UI consistent 

### PR DESCRIPTION
**Pull request by MichaScant**
# 🔗 Issue
Issue#1082 

# ✍️ Description
Fixed the UI changes required for issue #1082. These involved ensuring the pets tab under staff had the same setup and cards as pet_tasks. In addition, I've also reduced the filter width for consistency and to make sure the pet filters line up in one line rather than 2.

# 📷 Screenshots/Demos
Screenshot 2024-10-28 at 12 39 15 PM
Screenshot 2024-10-28 at 12 39 04 PM

### CODE REVIEW

**Comment by MichaScant** [comment]
Hey @kasugaijin my tests on the system are starting to fail upon merging with main. Should I attempt to resolve this, or is this listed in another issue?

**Comment by jmilljr24** [comment]
> Hey @kasugaijin my tests on the system are starting to fail upon merging with main. Should I attempt to resolve this, or is this listed in another issue?

@MichaScant I re-ran the tests and everything passed. It didn't appear to have anything to do with your changes so you should be good to go until someone gets a chance to review. Thanks!

**Comment by MichaScant** [comment]
Ok thank you for confirming! I was confused as I couldn't' find the cause and they were passing on my end

**Comment by jmilljr24** [comment]
@all-contributors
please add @MichaScant  for code.

**Review by kasugaijin — APPROVED** [review]
@MichaScant looks great! Thank you.

**Pull request merged**
