### PR TITLE
Update testing image added to page

### PR DESCRIPTION
**Pull request by ErinClaudio**
# 🔗 Issue
https://github.com/rubyforgood/pet-rescue/issues/990

# ✍️ Description
Images are sourced from screenshots - **_Please let me know if the images are off in sizing and if I should use Figma_**. 

# 📷 Screenshots/Demos
screencapture-localhost-3000-alta-staff-custom-page-edit-2024-10-01-11_17_15
Screenshot 2024-10-01 at 11 19 11 AM

### CODE REVIEW

**Comment by ErinClaudio** [comment]
@kasugaijin 
I may need to change the position of the image on mobile.

**Comment by kasugaijin** [comment]
@ErinClaudio I will ask one of our design folks to add a red border around the pertinent sections in each image - I think that will help communicate the relevant sections better.

**Comment by ErinClaudio** [comment]
@kasugaijin 
I can adjust the Red how ever you would like.

Screenshot 2024-10-04 at 1 11 26 PM
Screenshot 2024-10-04 at 1 11 12 PM

**Comment by kasugaijin** [comment]
> @kasugaijin I can adjust the Red how ever you would like.
> 
> Screenshot 2024-10-04 at 1 11 26 PM Screenshot 2024-10-04 at 1 11 12 PM

Ah cool! Can you please make the red boxes as follows?
image

**Comment by kasugaijin** [comment]
@ErinClaudio any blockers on this one? No rush...just checking

**Comment by kasugaijin** [comment]
Hey @ErinClaudio I will open this up for someone to finish. Thanks for work so far.

**Review by kasugaijin — APPROVED** [review]

**Review by kasugaijin — APPROVED** [review]

**Pull request merged**
