### PR TITLE
1097 - Update Sign Up form UI 

### PR DESCRIPTION
**Pull request by Meri-MG**
# 🔗 Issue
#1097 

# ✍️ Description
Sign up form UI should look like Log in form UI.

# 📷 Screenshots/Demos
Screenshot 2024-12-11 at 20 58 15

### CODE REVIEW

**Comment by Meri-MG** [comment]
Hi, @jmilljr24 , I merged main branch in but i dont see the new logo in the pages

**Comment by jmilljr24** [comment]
> Hi, @jmilljr24 , I merged main branch in but i dont see the new logo in the pages

There isn't a default image. I just uploaded a photo from my computer. Anything image you have available to attach should work that is mostly square shape as that is what logo's will most likely be.

**Comment by jmilljr24** [comment]
I don't think we have any constraints on photo dimensions for uploads though. So for the time being you will probably need to adjust the photo on the frontend. We have something similar on the org home index page. ` class="ratio ratio-1x1 w-100 border border-0"` . Check out bootstrap docs. Adjust according for size etc...

**Comment by kasugaijin** [comment]
@Meri-MG how's this one going? Let us know if you have any questions.

**Comment by Meri-MG** [comment]
> @Meri-MG how's this one going? Let us know if you have any questions.

ohhh, it's been two weeks, for some reason I thought the branch was merged, will address @jmilljr24 feedback at the end of this week

**Comment by Meri-MG** [comment]
Screenshot 2024-12-11 at 17 05 23


are we okay with this kind of layout? or should the image be smaller?

**Comment by kasugaijin** [comment]
> Screenshot 2024-12-11 at 17 05 23
> are we okay with this kind of layout? or should the image be smaller as below?
> 
> Screenshot 2024-12-11 at 17 07 24

@Meri-MG haha nice picture. Given it is a logo it should be small, like 30x30 pixels

**Review by jmilljr24 — APPROVED** [review]
@Meri-MG Looks good. Thanks

**Pull request merged**
